/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vending.machine;

public class App {
    public static void main(String[] args) {
        VendingMachineFactory.createVendingMachine();
    }
}
